### PR TITLE
Feature - Sort Namelist Feature

### PR DESCRIPTION
**Pull request by diwako**
Adressing #82 

Server syncs the array that is returned by running `units _player` to everyone, in theory it should synchronize the namelist.

Usage:
If DUI running on the server, the synchronization process will start automatically, clients will attempt to tell the server to run the sync, but the server will not start a second sync PFH.

If DUI is not running on the server, clients will share the synchronization function to the server and tell it to run it. This however will not work on server running Battle eye due to the CfgRemoteExec limitations.

### CODE REVIEW

**Comment by Drofseh** [comment]
Would it be possible to have a setting for the order in which units appear?
I'd personally like the team colours to always be grouped in the list, i could see wanting alphabetical as well. 
Leader first always I guess though.

**Comment by diwako** [comment]
@Drofseh not really. I do not want any sorting feature in DUI as the namelist must be the same for everyone. If options to sort are introduced everyone is going to use what ever they want and will cause confusion on row calls.
This PR is pretty much so the namelist order is consistent between all machines.

**Comment by diwako** [comment]
Added a setting for this now. Default will be set to `false` so server owners need to run dui on server and set it either in mission or on server if they want to use this feature.

**Comment by diwako** [comment]
This Pr will be changed to a PR regarding sorting the namelist. Synchronicity will be guaranteed as long the server runs DUI

**Comment by diwako** [comment]
CBA settings, all of them will be global settings!
- Check box for "SQL always topmost" (DEFAULT: false)
- Drop down box for sorting types
 -- None (Arma 3 inhouse sorting, will include current synchronize PFH) (DEFAULT)
 -- Names
 -- FireTeams (sort by name within fireteam)

**Comment by diwako** [comment]
image
Ordering by fire team (by name inside fire team)

image

**Comment by Drofseh** [comment]
I'd prefer white be listed before RGBY team colours, but not big deal if you want to keep it this way.

**Comment by diwako** [comment]
> I'd prefer white be listed before RGBY team colours, but not big deal if you want to keep it this way.

The values for the fire team and rank sorting are in a namespace, you can easily edit it even mid mission and it will take effect. `GVAR(sortNamespace)`

The reason white is the last one in line is because vanilla does it like this as well if you assign team colors.

**Pull request merged**
