### PR TITLE
isSpeaking feature changes after feedback

### PR DESCRIPTION
**Pull request by diwako**
Adds a toggle if the unit icon should be replaced with the speaking icon or if it should be placed behind the name.

image

### CODE REVIEW

**Comment by synixebrett** [comment]
Could there maybe be two icons? A speech bubble and a radio icon?

**Comment by diwako** [comment]
> Could there maybe be two icons? A speech bubble and a radio icon?

Find me a matching radio icon

**Comment by 10Dozen** [comment]
radio_icon

I draw something like this if you need.

**Comment by diwako** [comment]
That is also a possibility, I was hoping to find a suitable icon in the base game.
There were two I wanted to try out at some point, tho real life just happens sometimes. So I am unsure and have not checked in game how the look like. The two icons are those:
image
image


Having more options is always better as DUI has more icon styles, so creating icons is definitely not a waste.

**Comment by diwako** [comment]
Just pushed an update. TFAR still untested as of now.

Added radio icon that only shows up when talking/receiving over radio. There was feedback that local talking icon should only show up if that person is also in radar range. The radio icon will show up regardless or range in the namelist.

**Pull request merged**
