### PR TITLE
Support for GM compasses

### PR DESCRIPTION
**Pull request by diwako**
Addressing #94

And a little extra for maybe IFA compasses in the future. Added support for compasses using less than 360°

image
image

### CODE REVIEW

**Comment by Drofseh** [comment]
Those compasses aren't using degrees at all. They are using mils.
They go from 0 to 6399 mils.

**Comment by diwako** [comment]
@Drofseh the first one does 64 (mils) the second one does only 60 as far as i can see.

**Comment by Drofseh** [comment]
Ahh, sorry.
The first one is a NATO compass that is 6400 mils.
The second is a Warsaw Pact compass that is 6000 mils.
They used different sized mils.

https://en.wikipedia.org/wiki/Milliradian#Definitions_for_maps_and_artillery

**Comment by diwako** [comment]
I'd prefer them staying in the 60/64 area, as most people do not know this and think something is wrong when the compass it self got only up to 60/64

**Comment by Drofseh** [comment]
I have never disagreed with you more lol.

Make it a setting? I would hate it if it didn't show the correct numbers.

**Comment by Drofseh** [comment]
Additionally though, Arma also uses mils for some things.
Ace Mortars for example.

**Comment by diwako** [comment]
> Additionally though, Arma also uses mils for some things.
> Ace Mortars for example.

For actual milradians for mortars there already is a setting which shows milradians alongside the 360° bearing.

**Comment by Drofseh** [comment]
Is your concern mostly that people won't understand why it's 100 times the number shown on the compass?
If that's the case I think you aren't giving people enough credit. They'll figure it out quickly.

If it's the accuracy that's a concern, since mils are more accurate than degrees, then you could have it round to the nearest 50 or 100 mils. 1600, 1650, 1700, 1750, etc.

Either way I think making it 100x less that the actual correct bearing is a really bad idea.

**Comment by diwako** [comment]
Changed the compasses to 6000/6400 to actually use mils

**Pull request merged**
