### PR TITLE
Update Japanese translation

### PR DESCRIPTION
**Pull request by classicarma**
- Improved translation
- Supported to new entries

### CODE REVIEW

**Comment by diwako** [comment]
Once again, thank you.

**Comment by diwako** [comment]
Pushed to DEV steam workshop item for preview.

**Comment by classicarma** [comment]
@diwako nice. BTW, Why Icon names and Color Scheme isn't be translatable?

**Comment by diwako** [comment]
@classicarma mostly because I am lazy and did not expect anyone to provide translations. I can add some string tables for the icons, colors and radar styles as well.

**Comment by classicarma** [comment]
@diwako I see.

**Comment by diwako** [comment]
@classicarma Added support for translations for color, icon and compass stlyes. Also the part in the CBA settings which says "- Main" or "- Radar"

Commit: f32845a2eb963cd67af5e6f8a0b119c88b5b5911

**Pull request merged**
